[flarum]
url = "siteurl" # 你的 Flarum 站点地址。
username = "your_username_here" # 你的 Flarum 用户名
password = "your_password_here" # 你的 Flarum 账号密码

[bot]
ai_provider = "siliconflow" # 此处填写 siliconflow 或 openai 或 deepseek 或 gemini，这是 LLM。
image_provider = "siliconflow" # 此处填写 siliconflow 或 openai 或 deepseek 或 gemini，注意这是 VLM。
system_prompt = "你是一个友好的 AI 助手，擅长编程等领域，会帮助用户解决各类问题，输出使用 Markdown 格式。"
check_interval = 5

[tags]
# 这个列表是 AI 会主动回复的标签，建议单独为 AI 建立标签，防止污染论坛环境。
# 要注意，这里填写的是标签的英文名
whitelist = [ "ai-qa" ]

[openai]
api_key = "your_openai_api_key"
base_url = "https://api.openai.com/v1"
model = "gpt-5" # GPT 5 更好用。

[deepseek]
api_key = "your_deepseek_api_key"
base_url = "https://api.deepseek.com/v1"
model = "deepseek-chat" # 推荐就用这个。

[gemini]
api_key = "your_gemini_api_key"
model = "gemini-pro" # 推荐使用 Gemini Pro，会得到更好的效果。

[siliconflow]
api_key = "your_siliconflow_api_key"
base_url = "https://api.siliconflow.cn/v1/"
model = "Qwen/Qwen3-32B" # 推荐使用该模型。
